# Generated by Django 3.1.4 on 2021-02-10 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210128_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
