# Generated by Django 3.1.4 on 2021-02-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todo_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_due',
            field=models.BooleanField(default=False),
        ),
    ]
