# Generated by Django 3.1.4 on 2021-03-10 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_todo_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.todo')),
            ],
        ),
    ]
